### PR TITLE
Feature-Branch/wip

### PR DESCRIPTION
**Pull request by notrexxx**
This project fulfills the requirements set by the microverse guidelines

The commit message follows guidelines

Changes have been added (for bug fixes / features)

Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @notrexxx and @disc3110 
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [x] MIT license is missing from the README file.
- [x] Live link is not working in the README file.
- [x] Add navigation link on logo image in navbar.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
- [x] Use a signal image in The Theory of Inflation like [original page image](https://static01.nyt.com/newsgraphics/2014/03/18/theory-of-inflation/1ebaa1b972edda0f407fbaa0e010f6b50fb6792e/inflation-720.png).
- [x] Add `Editor's picks` section on the righmost side. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by notrexxx** [comment]
> # Status: REQUIRED CHANGES ⚠️ 🚧
> Hi @notrexxx and @disc3110
> Such a remarkable project you made 👍 ! Awesome README 💯 !
> We, however, do have a few changes to carry out before we proceed (see review comment).
> 
> Kindly work on the suggested changes 👇.
> 
> * [x]  MIT license is missing from the README file.
> * [x]  Live link is not working in the README file.
> * [x]  Add navigation link on logo image in navbar.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
> * [x]  Use a signal image in The Theory of Inflation like [original page image](https://static01.nyt.com/newsgraphics/2014/03/18/theory-of-inflation/1ebaa1b972edda0f407fbaa0e010f6b50fb6792e/inflation-720.png).
> * [x]  Add `Editor's picks` section on the righmost side. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
> 
> * **When you have made the specified changes, please submit another code review. Thank you!**
> 
> **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
> HAPPY CODING 💻
> **[Umair Arshad](https://umairarshad.me/)**
> [Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

Hello!, 

Thanks for the review.

I have done all of the revisions but one, the MIT license... I'm not sure what I need to fill in that part, can you help me?

Thanks, regards.

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @notrexxx and @disc3110 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Live link is still missing
- [ ] Remove horizontal scrollbar. (see the [video](https://www.loom.com/share/fba6bb6b70294121b51c6544f1857d0c))
### The Theory of Inflation
- [ ] Manage the text on image properly like source page.

|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://rawcdn.githack.com/notrexxx/NYT-HTML-CSS-Proyect/New/wip/index.html)|
|:---:|:---:|
|source-page|clone|




##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by notrexxx** [comment]
> # Status: REQUIRED CHANGES ⚠️ 🚧
> Hi @notrexxx and @disc3110
> Good job with the changes! 🎉 We are almost there.
> We, however, do have a few changes to carry out before we proceed (see review comment).
> 
> For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
> 
> * [ ]  Live link is still missing
> * [ ]  Remove horizontal scrollbar. (see the [video](https://www.loom.com/share/fba6bb6b70294121b51c6544f1857d0c))
> 
> ### The Theory of Inflation
> * [ ]  Manage the text on image properly like source page.
> 
> [Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)	[Clone Page](https://rawcdn.githack.com/notrexxx/NYT-HTML-CSS-Proyect/New/wip/index.html)
> source-page	clone
> * **When you have made the specified changes, please submit another code review. Thank you!**
> 
> **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
> HAPPY CODING 💻
> **[Umair Arshad](https://umairarshad.me/)**
> [Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

Hello!,

Thanks for the review.

Regarding the live link that is on the README.md page: https://notrexxx.github.io/NYT-HTML-CSS-Proyect/ ...It works for me and it's the same one that's placed on the README.md page.

In my live view, I don't have a horizontal scroll bar nor have any issues with the positioning of the text.

Regards

**Comment by umairarshadbutt** [comment]
Hi @notrexxx 
You can see in the [video](https://www.loom.com/share/a4cd42b9f95643d8b28776cd11bee2b9) that the Live link is not working. You can share your screenshot, video, or conduct a call with TSE.


HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by notrexxx** [comment]
> Hi @notrexxx
> You can see in the [video](https://www.loom.com/share/a4cd42b9f95643d8b28776cd11bee2b9) that the Live link is not working. You can share your screenshot, video, or conduct a call with TSE.
> 
> HAPPY CODING 💻
> **[Umair Arshad](https://umairarshad.me/)**
> [Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

Hello! @umairarshadbutt 

Here is a  [video](https://www.loom.com/share/61544a592242410d830097057723db98) of me clicking on the link and going to the live page. 

I don't understand why is not working

**Comment by umairarshadbutt** [comment]
Hi @notrexxx 
You can review your GitHub pages setting or you can use [raw.githack.com](https://raw.githack.com/) for Live Link

**Comment by notrexxx** [comment]
screenshot-github com-2021 01 14-03_25_36

Here is a screenshot of my settings, there is nothing I can change. I can access the live page normally, and with a VPN too. Also my coding partner and my stand up team were able to access it.

**Comment by umairarshadbutt** [comment]
Hi @notrexxx 
You can submit for re-review

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Diego Solis Cuevas & Andres Leon Alfonz** 
Good job with your first submission for this project :muscle:  :muscle:
Your page meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] Group selectors with the same style definition
- [x] Remove horizontal scrollbar
- [x] In The Theory of Inflation section, the text is overlapping the images in the background

| Yours | Original |
|:---:|:---:|
|image | image |
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by notrexxx** [comment]
> ### Status: Changes Required ♻️
> **Hello Diego Solis Cuevas & Andres Leon Alfonz**
> Good job with your first submission for this project 💪 💪
> Your page meets most of the requirements 👏 👏 👏
> There are just a few details to improve before you can go ahead:
> 
> * [ ]  Group selectors with the same style definition
> * [ ]  Remove horizontal scrollbar
> * [ ]  In The Theory of Inflation section, the text is overlapping the images in the background
> 
> Yours	Original
> image	image
> Please request another review once you are ready! 👍
> 
> Happy coding ☺️
> 
> Oscar Andrés Russi Porras

Hello! @andresporras3423 

Thank you for the review.

I have fixed the issues in the theory of inflation section, the text is no longer overlapping.

I also looked for group selectors with the same style definition and grouped them in one and removed repeating styles. 

The scroll bar was showing because I was not nesting properly the aside inside the section and I had to use a very large maring-left to make it look ok, but I have fixed it now!.

Thank you, regards!

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @notrexxx and @disc3110 :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this project can be approved.

## REQUIRED

* [x] Please, make all the changes as requested by the previous TSE.
* [x] The video and images on your page should be centred.
* [x] Add some margin/padding to the aside tag so that it doesn't get too close to the main content.

### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by notrexxx** [comment]
> # Status: Changes Required ♻️
> ## Hi @notrexxx and @disc3110 👋
> You've done well so far 👍 and I commend you for that 👏
> However, there are still some changes to be made before this project can be approved.
> 
> ## REQUIRED
> * [x]  Please, make all the changes as requested by the previous TSE.
> * [x]  The video and images on your page should be centred.
> * [x]  Add some margin/padding to the aside tag so that it doesn't get too close to the main content.
> 
> ### Make the requested changes and submit for another review.
> ## Happy Coding 💻
> _Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
> **Elijah O. Ayandokun**
> [Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

Hello!

Thanks for the review.

I have made the changes requested by the previous TSE (overlapping text in the theory of inflation, the horizontal scroll bar, and the group selectors).

Now I have changed the youtube video and the third image that were not rising or centered and changed the margin of the aside box.

Thank you!

**Review by voscarmv — APPROVED** [review]
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
